### ISSUE TITLE
"docker build" argument has to be last (for older docker versions?)

### ISSUE THREAD

**Issue by eserte** [osakech/pm-debianizer#1]
In my docker version (`1.6.2~dfsg1-1~bpo8+1` from jessie-backports) the following diff in pmd.pl seems to be needed:
```
-my $bCont = "docker build . -t $containerName -f Dockerfile";
+my $bCont = "docker build -t $containerName -f Dockerfile .";
```
That is, the "." argument has to be at the end.

**Comment by osakech** [comment]
Hi Slaven, thanks for opening an issue. In release 0.2 the "." is in the end of the command.
